name: mruby-llm

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: mruby-llm
    - uses: actions/checkout@v4
      with:
        repository: mruby/mruby
        path: mruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y bison libcurl4-openssl-dev
    - name: Build and test
      run: |
        cd mruby-llm
        make MRUBY_DIR=${{ github.workspace }}/mruby CURLDIR=/usr
